/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Engine is alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status?: "ok";
                            version?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (DB + storage reachable) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ready */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not ready */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/play/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        /**
         * Self-contained iframe player page
         * @description Returns an HTML page that loads the SCO, injects the SCORM runtime API
         *     (`window.API` / `window.API_1484_11`), and persists progress to this engine.
         *     Host with a single `<iframe>` — no SDK or framework required.
         */
        get: {
            parameters: {
                query: {
                    /** @description Attempt JWT (issued by `/auth/attempt-token`). */
                    token: string;
                    theme?: "light" | "dark" | "auto";
                    /** @description Optional — override the default SCO. */
                    scoId?: string;
                };
                header?: never;
                path: {
                    attemptId: components["parameters"]["AttemptId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description HTML player page */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/html": string;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runtime.js": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Standalone SCORM runtime bridge script
         * @description Returns a small JS file that, when included via `<script>`, exposes
         *     `window.API` (SCORM 1.2) and `window.API_1484_11` (SCORM 2004) wired to
         *     this engine. A clean-room, spec-compliant implementation — no third-party
         *     SCORM libraries are bundled or required. The SCO inside an `<iframe>`
         *     finds the globals via the normal SCORM lookup walk (parent, then opener)
         *     and behaves exactly as it would against any conformant LMS.
         *
         *     ```html
         *     <script src="https://your-engine/runtime.js?attemptId=...&token=..."></script>
         *     <iframe src="./course/index.html"></iframe>
         *     ```
         */
        get: {
            parameters: {
                query: {
                    attemptId: string;
                    /** @description Attempt JWT (issued by `/auth/attempt-token`). */
                    token: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JavaScript runtime bridge */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/javascript": string;
                        "text/javascript": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/attempt-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a short-lived JWT scoped to a single attempt
         * @description Called by the LMS backend to mint a token the browser-side player can use
         *     without exposing the long-lived API key. Token TTL defaults to the attempt
         *     duration limit (configurable, max 24h).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        attemptId: string;
                        /** @default 3600 */
                        ttlSeconds?: number;
                    };
                };
            };
            responses: {
                /** @description Token issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            token?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List courses */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    /** @description Opaque pagination cursor returned by the previous page. */
                    cursor?: components["parameters"]["Cursor"];
                    /** @description Free-text search on course title. */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated course list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Upload a SCORM package
         * @description Accepts a SCORM 1.2 or 2004 ZIP package. The engine extracts the package,
         *     parses `imsmanifest.xml`, persists metadata, and stores the package files
         *     via the configured storage adapter.
         *
         *     For large files prefer the two-step flow:
         *     1. `POST /courses/upload-url` to get a presigned upload URL.
         *     2. `POST /courses` with `{ uploadKey }` to register the uploaded package.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /**
                         * Format: binary
                         * @description SCORM package ZIP.
                         */
                        file: string;
                        /** @description Override the title parsed from the manifest. */
                        title?: string;
                    };
                    "application/json": {
                        /** @description Storage key returned by /courses/upload-url */
                        uploadKey: string;
                        title?: string;
                    };
                };
            };
            responses: {
                /** @description Course created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"];
                    };
                };
                400: components["responses"]["BadRequest"];
                /** @description Invalid SCORM package (malformed ZIP or manifest) */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/upload-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a presigned URL for direct package upload */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        filename: string;
                        sizeBytes: number;
                        /** @default application/zip */
                        contentType?: string;
                    };
                };
            };
            responses: {
                /** @description Upload URL issued */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            uploadUrl?: string;
                            uploadKey?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                            /** @enum {string} */
                            method?: "PUT" | "POST";
                            headers?: {
                                [key: string]: string;
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        /** Get a course */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Course */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        /** Delete a course and all its attempts */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/launch-url": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        /**
         * Get a signed launch URL for the course's primary SCO
         * @description Returns a short-lived URL pointing at the SCO entry point on the engine's
         *     static asset host. The player loads this in an iframe.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Optional — defaults to the manifest's primary SCO. */
                    scoId?: string;
                };
                header?: never;
                path: {
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Launch URL */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uri */
                            launchUrl?: string;
                            /** Format: date-time */
                            expiresAt?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate a SCORM package without registering it
         * @description Useful for CI / authoring pipelines. No course is persisted.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Validation report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ValidationReport"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start or resume an attempt
         * @description Starts a new attempt for a learner against the course, or resumes the
         *     learner's existing in-progress attempt for the same SCO. A fresh attempt
         *     launches `ab-initio`; a resumed one launches `resume` and returns its last
         *     committed CMI snapshot so the player can rehydrate the SCO.
         *
         *     Pass `restart: true` to force a brand-new attempt even when a resumable
         *     one exists.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Opaque identifier from the host LMS. The engine never stores PII —
                         *     this is the only learner identifier it knows.
                         */
                        learnerId: string;
                        /** @description Optional display name passed to the SCO as `student_name`. */
                        learnerName?: string;
                        /** @description Target SCO; defaults to the course's primary SCO. */
                        scoId?: string;
                        /**
                         * @default normal
                         * @enum {string}
                         */
                        mode?: "normal" | "browse" | "review";
                        /**
                         * @description Force a new attempt instead of resuming an open one.
                         * @default false
                         */
                        restart?: boolean;
                    };
                };
            };
            responses: {
                /** @description Existing in-progress attempt resumed. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StartAttemptResponse"];
                    };
                };
                /** @description New attempt created (ab-initio). */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StartAttemptResponse"];
                    };
                };
                400: components["responses"]["BadRequest"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        /**
         * Get an attempt
         * @description Returns the attempt's rolled-up state plus its objective and interaction rows.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attemptId: components["parameters"]["AttemptId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attempt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Attempt"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        /**
         * Get the runtime state for (re)hydrating a SCO
         * @description Returns the CMI snapshot, SCORM version, and entry mode a player needs to
         *     initialize the SCO. `entry` is `resume` once the attempt has any committed
         *     CMI, otherwise `ab-initio`. This is the read side of the runtime loop; use
         *     the start-attempt response for the initial launch and this endpoint to
         *     re-fetch state (e.g. after a reload) without creating a new attempt.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attemptId: components["parameters"]["AttemptId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runtime state */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeState"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attemptId}/commit": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attemptId: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Commit a batch of CMI value changes
         * @description Replays a batch of `SetValue` writes through an authoritative server-side
         *     runtime session seeded from the attempt's last snapshot, then persists the
         *     result. The player should call this:
         *     - On `LMSCommit` / `Commit` from the SCO.
         *     - On a debounced interval (e.g. every 10s) to reduce data-loss risk.
         *     - On `beforeunload` (with `keepalive: true`).
         *
         *     Set `terminate: true` to close the session out (`LMSFinish` / `Terminate`),
         *     performing a final commit and finalizing the attempt.
         *
         *     Keys use SCORM-version-native naming:
         *     - SCORM 1.2: `cmi.core.lesson_status`, `cmi.suspend_data`, ...
         *     - SCORM 2004: `cmi.completion_status`, `cmi.success_status`, ...
         *
         *     **Validation policy** (server-configured via `SCORM_VALIDATION_MODE`):
         *     - `lenient` (default): mirrors certified commercial LMSes — writes that
         *       fail validation are still persisted and reported in `warnings`. SCORM
         *       content in the wild routinely violates the spec, and rejecting commits
         *       would break otherwise-functional courses. A single bad write never
         *       aborts the batch, so `ok` stays `true`.
         *     - `strict`: writes that fail validation are dropped and reported in
         *       `errors` (`ok` is `false`), for conformance-testing content. Valid
         *       writes in the same batch still persist.
         *
         *     Either way the commit as a whole succeeds; inspect `errors`/`warnings` for
         *     per-element detail, not for retry control flow.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    attemptId: components["parameters"]["AttemptId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommitRequest"];
                };
            };
            responses: {
                /** @description Commit accepted (possibly with warnings or per-element errors). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CommitResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
                /** @description Attempt already finished. */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant-wide analytics overview */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Overview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AnalyticsOverview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        /** Analytics for a single course */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: components["parameters"]["CourseId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Course analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CourseAnalytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/learners/{learnerId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                learnerId: string;
            };
            cookie?: never;
        };
        /** Analytics for a single learner */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    learnerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Learner analytics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LearnerAnalytics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable machine-readable error code (e.g. `course_not_found`). */
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
            requestId?: string;
        };
        Pagination: {
            nextCursor?: string | null;
            hasMore?: boolean;
        };
        /** @enum {string} */
        ScormVersion: "SCORM_1_2" | "SCORM_2004_2" | "SCORM_2004_3" | "SCORM_2004_4";
        Course: {
            /** Format: uuid */
            id: string;
            title: string;
            description?: string | null;
            version: components["schemas"]["ScormVersion"];
            /** @enum {string} */
            status: "processing" | "ready" | "failed";
            scos?: components["schemas"]["Sco"][];
            /** @description Default SCO launched when the player starts. */
            primaryScoId?: string;
            /** @description 0-100 mastery threshold parsed from the manifest. */
            masteryScore?: number | null;
            manifest?: components["schemas"]["ManifestMetadata"];
            sizeBytes?: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Sco: {
            id: string;
            /** @description Manifest `identifier` attribute. */
            identifier: string;
            title: string;
            /** @description Relative path within the package to the SCO entry point. */
            launchHref: string;
            parameters?: string | null;
            masteryScore?: number | null;
        };
        ManifestMetadata: {
            identifier?: string;
            title?: string;
            description?: string | null;
            keywords?: string[];
            schemaVersion?: string;
            defaultOrganization?: string | null;
        };
        CourseListResponse: {
            data?: components["schemas"]["Course"][];
            pagination?: components["schemas"]["Pagination"];
        };
        ValidationReport: {
            valid?: boolean;
            version?: components["schemas"]["ScormVersion"] | null;
            errors?: {
                code?: string;
                message?: string;
                path?: string | null;
            }[];
            warnings?: {
                code?: string;
                message?: string;
            }[];
        };
        Attempt: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            courseId: string;
            learnerId: string;
            learnerName?: string | null;
            /** @description 1-indexed sequence of attempts by this learner on this course. */
            attemptNumber: number;
            /** @enum {string} */
            status: "not_started" | "in_progress" | "completed" | "passed" | "failed" | "terminated";
            /**
             * @description SCORM 2004 completion status; mapped from `cmi.completion_status`.
             * @enum {string}
             */
            completionStatus?: "unknown" | "completed" | "incomplete" | "not_attempted";
            /**
             * @description SCORM 2004 success status; mapped from `cmi.success_status`.
             * @enum {string}
             */
            successStatus?: "unknown" | "passed" | "failed";
            score?: components["schemas"]["Score"];
            progressMeasure?: number | null;
            /** @description Total accumulated session time across all sessions in this attempt. */
            totalTimeSeconds?: number;
            /** @description Bookmark (`cmi.core.lesson_location` / `cmi.location`). */
            location?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            lastAccessedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        Score: {
            raw?: number | null;
            min?: number | null;
            max?: number | null;
            /** @description SCORM 2004 normalized score (-1..1). */
            scaled?: number | null;
        };
        RuntimeState: {
            /** Format: uuid */
            attemptId: string;
            version: components["schemas"]["ScormVersion"];
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED" | "TERMINATED" | "EXPIRED";
            /**
             * @description Full CMI data model snapshot, keyed by SCORM-native paths. Empty object
             *     for a new attempt; for a resume, contains every previously-committed key.
             * @example {
             *       "cmi.core.lesson_status": "incomplete",
             *       "cmi.core.lesson_location": "page_4",
             *       "cmi.suspend_data": "{\"chapter\":2,\"answers\":[1,3,2]}",
             *       "cmi.core.score.raw": 42
             *     }
             */
            cmi: {
                [key: string]: unknown;
            };
            /**
             * @description SCORM `cmi.core.entry` / `cmi.entry`.
             * @enum {string}
             */
            entry: "ab-initio" | "resume";
            learner: {
                id: string;
                name?: string | null;
            };
        };
        StartAttemptResponse: {
            /** Format: uuid */
            attemptId: string;
            /** @description True when an existing in-progress attempt was resumed. */
            resumed: boolean;
            version: components["schemas"]["ScormVersion"];
            /**
             * @description SCORM `cmi.core.entry` / `cmi.entry` the SCO should launch with.
             * @enum {string}
             */
            entry?: "ab-initio" | "resume" | "";
            /** @description Read-only launch context the player injects before Initialize. */
            launch?: {
                learnerId?: string;
                learnerName?: string;
                /** @enum {string} */
                mode?: "normal" | "browse" | "review";
                /** @description Accumulated time from prior attempts, in the edition's timespan format. */
                totalTime?: string;
                masteryScore?: number | null;
            };
            /**
             * @description Previously-committed CMI snapshot to rehydrate the SCO on resume. Empty
             *     object for a new (ab-initio) attempt.
             * @example {
             *       "cmi.location": "page_4",
             *       "cmi.suspend_data": "{\"chapter\":2}"
             *     }
             */
            cmi: {
                [key: string]: unknown;
            };
        };
        CommitRequest: {
            /**
             * @description CMI writes to replay, as an object of key → value pairs or an ordered
             *     array of `[key, value]` pairs (use the array form when write order
             *     matters). Keys must match the SCORM version of the course.
             * @example {
             *       "cmi.completion_status": "completed",
             *       "cmi.score.scaled": "0.87",
             *       "cmi.session_time": "PT12M30S"
             *     }
             */
            values: {
                [key: string]: string;
            } | string[][];
            /**
             * @description When true, Terminate the session (final commit) and finalize the
             *     attempt instead of leaving it open for further commits.
             * @default false
             */
            terminate: boolean;
        };
        CommitResponse: {
            /** @description False only in strict mode when one or more writes were rejected. */
            ok: boolean;
            /** @description True when this commit finalized the attempt. */
            terminated: boolean;
            /** @description Writes rejected in strict mode (not persisted). Empty in lenient mode. */
            errors: components["schemas"]["CommitIssue"][];
            /**
             * @description Nonconformant writes accepted in lenient mode (persisted verbatim).
             *     Empty in strict mode. Use for observability, not retry logic.
             */
            warnings: components["schemas"]["CommitIssue"][];
            summary: components["schemas"]["RuntimeSummary"];
        };
        CommitIssue: {
            /** @description The CMI element the write targeted. */
            element: string;
            /** @description SCORM API error code (edition-specific numeric code). */
            code: number;
            message: string;
        };
        /** @description Edition-neutral rollup of the outcome-bearing CMI elements. */
        RuntimeSummary: {
            /** @enum {string} */
            completionStatus?: "completed" | "incomplete" | "not attempted" | "unknown";
            /** @enum {string} */
            successStatus?: "passed" | "failed" | "unknown";
            scoreRaw?: number | null;
            scoreMin?: number | null;
            scoreMax?: number | null;
            scoreScaled?: number | null;
            progressMeasure?: number | null;
            lessonLocation?: string | null;
            suspendData?: string | null;
            sessionTime?: string | null;
            exit?: string | null;
        };
        AnalyticsOverview: {
            courseCount?: number;
            learnerCount?: number;
            attemptCount?: number;
            completionRate?: number;
            averageScore?: number | null;
        };
        CourseAnalytics: {
            /** Format: uuid */
            courseId?: string;
            attemptCount?: number;
            completionCount?: number;
            completionRate?: number;
            averageScore?: number | null;
            averageTimeSeconds?: number | null;
            passRate?: number | null;
            recentAttempts?: components["schemas"]["Attempt"][];
        };
        LearnerAnalytics: {
            learnerId?: string;
            attemptCount?: number;
            completedCourseCount?: number;
            totalTimeSeconds?: number;
            recentAttempts?: components["schemas"]["Attempt"][];
        };
    };
    responses: {
        /** @description Request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid credentials. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        CourseId: string;
        AttemptId: string;
        Limit: number;
        /** @description Opaque pagination cursor returned by the previous page. */
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
